INSERT INTO patient (PT_NUM, PT_NM, PT_SX, PT_BD, PT_EM)
SELECT DISTINCT PT_NUM, PT_NM, PT_SX, PT_BD, PT_EM
FROM aaaa;

INSERT INTO visit (VS_ID, PT_NUM, VS_DPMT, VS_TIME, VS_FEE, VS_STMT)
SELECT 
    DISTINCT CONCAT(LPAD(PT_NUM, 4, '0'), DATE_FORMAT(VS_TIME, '%Y%m%d')) AS VS_ID,
    PT_NUM,
    VS_DPMT,
    VS_TIME,
    VS_FEE,
    VS_STMT
FROM aaaa;